### ISSUE TITLE
Test #4: CSimpleReal64 Failed on macosx

### ISSUE THREAD

**Issue by jdh13** [scivision/mumps#1]
Hello,
i'm trying your build system on macosx without success. I did the same commands on macosx (Mojave) and Ubuntu 18 LTS.
On macosx, looking at `./build/Testing/Temporary/LastTest.log`:
```
4/9 Testing: CSimpleReal64
4/9 Test: CSimpleReal64
Command: "/Users/me/projets/mumps/build/tests/Csimple"
Directory: /Users/me/projets/mumps/build/tests
"CSimpleReal64" start time: Jan 08 16:28 CET
Output:
----------------------------------------------------------
 (PROC 68) ERROR RETURN:        INFOG(1)= -16
                                INFOG(2)= 0
<end of output>
Test time =   0.01 sec

```

I used the commands:
```
cmake -B build -Dparallel=false
cmake --build build --parallel
cmake --build build --target test 
```

Could you help me?

Thanks in advcance

**Comment by scivision** [comment]
I had an unnecessary variable that wasn't assigned. It appears it may have been causing this error. I removed this variable. I also added an option to disable this test, as many are not using MUMPS from C language.  `-DClangTest=false`

If you could try `git pull` from master branch and let us know if it's still an issue.  Worse case, a workaround is to use `-DClangTest=false`

**Comment by jdh13** [comment]
hello 
it works fine! Thanks for your help.
