### ISSUE TITLE
Mumps on Windows

### ISSUE THREAD

**Issue by TangLaoya** [scivision/mumps#3]
Dear administrator,
Thanks for providing the Cmake files. I tried on Windows 10 64bit + Visual Studio 2019 + Intel Fortran 2020, the following errors displayed:

`CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in C:/solver/mumps-master/64bit/CMakeFiles/CMakeTmp/CMakeLists.txt:
  Imported target "MPI::MPI_C" includes non-existent path

    "C:/Program Files (x86)/Intel/MPI/4.1.3.047/intel64/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/FindMPI.cmake:1194 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindMPI.cmake:1245 (_MPI_try_staged_settings)
  C:/Program Files/CMake/share/cmake-3.16/Modules/FindMPI.cmake:1505 (_MPI_check_lang_works)
  CMakeLists.txt:55 (find_package)

Configuring incomplete, errors occurred!
`

Could you please help me to take a look at it?

Thanks,
Tang Laoya

**Comment by scivision** [comment]
OK Thanks the Intel compiler on Windows is a setup we regularly use, so this is interesting, thanks for reporting!

**Comment by scivision** [comment]
There may be an issue with CMake: https://discourse.cmake.org/t/findblas-bug-with-intel-oneapi-compiler-on-windows/1493

**Comment by scivision** [comment]
Hmm, looking again, this issue may be distinct. It looks like CMake is trying to use a several year old version of Intel MPI.
If you're not using that old MPI, maybe consider uninstalling it?

Or, set environment variable MPI_ROOT to a value like "%MKLROOT%"\..\..\mpi\latest  -- the directory might be slightly different depending on Intel MPI version. That usually works to get CMake to find the correct MPI.

**Comment by scivision** [comment]
I will tentatively close this as I think this is an issue with CMake itself finding an old/undesired MPI.
It might be that if you make a separate CMake test, where you have a C-executable using MPI that it also would fail. 
I will add a test to MUMPS for broken MPI to help detect this type of problem.
