### ISSUE TITLE
Mumps on Windows compiled by Msys2 (mingw64)

### ISSUE THREAD

**Issue by rockydut** [scivision/mumps#4]
I want to comple the mumps on windows by mingw. I installed the msmpi and scalapack in msys2 by "pacman -S mingw-w64-x86-64-msmpi" and  "pacman -S mingw-w64-x86-64-scalapack". 
When I compile the mumps, the cmake error shows:

CMake Error at cmake/mpi.cmake:24 (message):
  MPI Fortran library mpif.h not functioning with GNU 10.2.0
Call Stack (most recent call first):
  CMakeLists.txt:57 (include)

Is there any method to compole mumps on windows by mingw?

**Comment by rockydut** [comment]
Furthermore, can any one precompile the mumps by mingw and put on it in msys2 pool? That will save a lot of troubles for the user in msys2.

**Comment by scivision** [comment]
https://www.scivision.dev/windows-mpi-msys2/ describes how to use MS-MPI in Fortran with MSYS2. I use MS-MPI with MinGW from MSYS2 in Fortran this way almost every day. I will add it to the Mumps Readme here. I think it would be nice to have this in MSYS2 I agree.

**Comment by rockydut** [comment]
Thank you for you quickly reply and thans for your contribute for the open source code. Hope the user can get mumps from msys2 repository just by a command: pacman -S mingw-w64-x86_64-mumps. That's very useful for some developer. You know, it is hard to config the MPI, Scotch and any other packages.
